@startuml "Diagramas de casos de uso"

skinparam {
	Backgroundcolor White
	Linetype Ortho
	ArrowColor Black
	Actor {
		Style Awesome
		BackgroundColor White
		FontColor Black
		BorderColor Black
		BorderThickness 2.5
	}
	Component {
		Style Rectangle
		FontColor Black
		BackgroundColor White
		BorderColor Black
		BorderThickness 2.5
	}
}

left to right direction

'_____________________________________________________________________________________________________________________
:Admin o Tecnico prevencionista: as "               Admin o\nTecnico/a prevencionista"
[Login Admin] as "Login"
:Admin o Tecnico prevencionista: -r-> [Login Admin]

[Registrarse Admin] as "Registrarse"
[Login Admin] <-r-> [Registrarse Admin]

[Calendario Admin] as "Calendario\nY Menu"
[Login Admin] -d-> [Calendario Admin]

[Gestor de arreglos Admin] as "Gestor de Arreglos"
[Calendario Admin] <-r-> [Gestor de arreglos Admin]

[Perfil Admin] as "Perfil"
[Calendario Admin] <-l-> [Perfil Admin]
'_____________________________________________________________________________________________________________________
:Guardia:
[Login Guardia] as "Login"
:Guardia: -r-> [Login Guardia]

[Calendario Guardia] as " Calendario\nSolo lectura"
[Login Guardia] -d-> [Calendario Guardia]

[Registrarse Guardia] as "Registrarse"
[Login Guardia] <-r-> [Registrarse Guardia]

[Perfil Guardia] as "Perfil"
[Calendario Guardia] <-l-> [Perfil Guardia]
'_____________________________________________________________________________________________________________________
:Empresa Terciarizada:
[Login Terciarizado E] as "Login"
:Empresa Terciarizada: -r-> [Login Terciarizado E]

[Registrarse E] as "Registrarse"
[Login Terciarizado E] <-r-> [Registrarse E]

[Informacion de trabajos pendientes E] as "Informacion de trabajos pendientes"
[Login Terciarizado E] -d-> [Informacion de trabajos pendientes E]

[Gestor de empleados terciarizados] as "Gestor de empleados"
[Informacion de trabajos pendientes E] <-l-> [Gestor de empleados terciarizados]

[Postularse a realizar un arreglo]
[Informacion de trabajos pendientes E] <-r-> [Postularse a realizar un arreglo]
'_____________________________________________________________________________________________________________________


@enduml
