@startuml "Diagrama_de_la_Base_de_datos"

skinparam {
	BackgroundColor white
	LineType Ortho
	ArrowColor Black
	Entity {
		FontColor Black
		BackgroundColor White
		BorderColor Black
	}
}

entity "Sucursales" {
    * ID : BigInt Autoincrement
	--
	* Nombre : Text
}

entity "Documentos" {
	* Pertenece A : BigInt <<FK>>
	* Archivo : Blob
}

entity "Usuarios" {
    * ID : BigInt Autoincrement
    --
    * Nombre : String
    * Email : String
    * Contraseña : String
    * Tipo_de_usuario : Enum [Administrador, Guardia, Empresa]
}

entity "Solicitudes de Registro" {
    * ID: BigInt Autoincrement
    --
    * Nombre: String
    * Email: String
    * Contraseña: String
    * Tipo_de_usuario : Enum [Administrador, Guardia, Empresa]

    * Created_at : Date
	* Updated_at : Date
}

entity "Detalles Guardia" {
    * Guardia: BigInt <<FK>>
    * Trabaja en: String
    * Created_at : Date
	* Updated_at : Date
}

entity "Notificaciones Administrador" {
    * ID : BigInt Autoincrement
    --
    * Nombre: String
    * Descripcion: String
    * Ruta: String
    * Tipe: Enum [Solicitud de registro]
    * Created_at : Date
	* Updated_at : Date
}

entity "Notificaciones Empresa" {
    * ID : BigInt Autoincrement
    --
    * Pertenece a: Int <<FK>>
    * Nombre: String
    * Descripcion: String
    * Ruta: String

    * Created_at : Date
	* Updated_at : Date
}

entity "Notificaciones Guardia" {
    * ID : BigInt Autoincrement
    --
    * Pertenece a: Int <<FK>>
    * Nombre: String
    * Descripcion: String
    * Ruta: String

    * Created_at : Date
	* Updated_at : Date
}

entity "Arreglos" {
	* ID : BigInt Autoincrement
	--
	* Nombre : Text
	* Descripcion : Text
	* Creado_por : Int <<FK>>
    * Empresa_encargada : Int <<FK>>
    * Personal_encargado: String
    * Sucursal : Int <<FK>>
    * Created_at : Date
	* Updated_at : Date
}

entity "Historial Arreglos" {
	* ID : BigInt Autoincrement
	--
	* Nombre : Text
	* Descripcion : Text
    * Creado_por : Json
      Empresa_encargada : Json
    * Personal_encargado: String
    * Sucursal : Json
    * Fecha_realizado: Date
    * Created_at : Date
	* Updated_at : Date
}


' Añadiendo las relaciones:
"Usuarios" ||-u-o{ "Documentos"
"Usuarios" ||-u-o| "Detalles Guardia"
"Usuarios" }o-r-|| "Arreglos"
"Usuarios" ||-d-o{ "Notificaciones Empresa"
"Usuarios" ||-d-o{ "Notificaciones Guardia"
"Arreglos" }o-d-|| "Sucursales"
"Arreglos" -[hidden]r- "Historial Arreglos"
"Usuarios" -[hidden]l- "Notificaciones Administrador"

' Puedo poner ':' despues de una relacion pa poner comentario en el medio

@enduml
