@startuml "Diagrama_de_la_Base_de_datos"

skinparam {
	BackgroundColor white
	LineType Ortho
	ArrowColor Black
	Entity {
		FontColor Black
		BackgroundColor White
		BorderColor Black
	}
}

'left to right direction

entity "Sucursales" {
	* Nombre : Text
	--
}

entity "Administradores" {
	* Cedula : Int
	--
	* Nombre : Text
}

entity "Guardias" {
	* Cedula : Int
	--
	* Nombre : Text
    * Trabaja_en : Json
}

entity "Empresas Terciarizadas" {
	* RUT : Int
	--
	* Nombre : Text
}

entity "Documentos de las empresas" {
	* ID : Int Autoincrement
	--
	* Pertenece A : Int <<FK>>
	* Archivo : Blob
}

entity "Trabajadores Terciarizados" {
	* Cedula : Int
	--
	* Nombre : Text
	* Trabaja_en : Int <<FK>>
}

entity "Documentos de los trabajadores" {
	* ID : Int Autoincrement
	--
	* Pertenece A : Int <<FK>>
	* Archivo : Blob
}

entity "Usuarios" {
    * ID : BigInt Autoincrement
    --
    * Nombre : String
    * Email : String
    * Contraseña : String
    * Tipo de usuario : Enum [Administrador, Guardia, Empresa, Trabajador]
}

entity "Arreglos" {
	* ID : Int Autoincrement
	--
	* Nombre : Text
	* Descripcion : Text
	* Creado_por : Int <<FK>>
	* Sucursal : Text <<FK>>
	* Fecha_creacion : Date
	  Fecha_realizado : Date
}

entity "Solicitudes de arreglo" {
	* ID : Int Autoincrement
	--
	* Creada_por : Int <<FK>>
	* Solicita_arreglar : Int <<FK>>
    * Estado : Enum [Aceptada, Rechazada, En espera]
	* Trabajadores_asignados: Json
	  Aprobada_por : Text <<FK>>
}

' Añadiendo las relaciones:
"Sucursales" ||-l-o{ "Guardias"
"Administradores" ||-d-o{ "Arreglos"
"Administradores" ||-d-o{ "Solicitudes de arreglo"
"Arreglos" }o-d-||"Sucursales"
"Arreglos" ||-l-o{ "Solicitudes de arreglo"
"Empresas Terciarizadas" ||-r-o{ "Solicitudes de arreglo"
"Empresas Terciarizadas" ||-l-o{ "Documentos de las empresas"
"Empresas Terciarizadas" ||-d-o{ "Trabajadores Terciarizados"
"Trabajadores Terciarizados" ||-l-o{ "Documentos de los trabajadores"

"Usuarios" --[hidden]r- "Administradores"

' Puedo poner ':' despues de una relacion pa poner comentario en el medio

@enduml
