@startuml "Diagrama_de_la_Base_de_datos"

skinparam {
	BackgroundColor white
	LineType Ortho
	ArrowColor Black
	Entity {
		FontColor Black
		BackgroundColor White
		BorderColor Black
	}
}

entity "Sucursales" {
	* Nombre : Text
	--
}

entity "Documentos" {
	* Pertenece A : BigInt <<FK>>
	* Archivo : Blob
}

entity "Usuarios" {
    * ID : BigInt Autoincrement
    --
    * Nombre : String
    * Email : String
    * Contraseña : String
    * Tipo_de_usuario : Enum [Administrador, Guardia, Empresa]
    * Roles : String
}

entity "Detalles Administrador" {
    * Administrador: Int <<FK>>
}

entity "Detalles Empresa" {
    * Empresa: Int <<FK>>
}

entity "Detalles Guardia" {
    * Guardia: Int <<FK>>
    * Trabaja en: String
}

entity "Arreglos" {
	* ID : Int Autoincrement
	--
	* Nombre : Text
	* Descripcion : Text
	* Creado_por : Int <<FK>>
    * Empresa_encargada : Int <<FK>>
    * Personal_encargado: String
	* Sucursal : Text <<FK>>
    * Created_at : Date
	* Updated_at : Date
}

entity "Historial Arreglos" {
	* ID : Int Autoincrement
	--
	* Nombre : Text
	* Descripcion : Text
	* Creado_por : Int <<FK>>
    * Empresa_encargada : Int <<FK>>
    * Personal_encargado: String
	* Sucursal : Text <<FK>>
    * Created_at : Date
	* Updated_at : Date
}


' Añadiendo las relaciones:
"Documentos" }o-r-|| "Usuarios"
"Usuarios" ||-d-o| "Detalles Administrador"
"Usuarios" ||-d-o| "Detalles Empresa"
"Usuarios" ||-d-o| "Detalles Guardia"
"Usuarios" }o-r-|| "Arreglos"
"Arreglos" }o-d-|| "Sucursales"
"Arreglos" -[hidden]r- "Historial Arreglos"

' Puedo poner ':' despues de una relacion pa poner comentario en el medio

@enduml
