@startgantt

title "Primera planificacion del grupo"
language es
printscale daily zoom 2
Project starts 2024-08-12
hide footbox

--Frontend:--
[Bocetado] starts D+0 and requires 11 days 
[Devuelta a la programacion] starts at [Bocetado]'s end and requires 2 weeks

--Backend:--
[Esquematizado y prototipado] starts D+0 and requires 1 week
[Comienzo de la programacion] starts at [Esquematizado y prototipado]'s end and requires 18 days

@endgantt
